/* 
lexer.h: declaration of global lexing vars and const

Student Project Compilers, 2009-2010

Dries Van Dyck
Department WNI
Theoretical Computer Science Group
Hasselt University 

januari 2010


History:
- 29/01/2010  Initial draft
- 25/02/2010  Removed inclusion of tokens.h to use tokens generated by Yacc

Bugs:

*/

#ifndef LEXER_H
#define LEXER_H

#include <stdio.h>

/* Include definition of tokenids */
/*#include "tokens.h"*/

/* Lex puts the value of the token under consideration in the global
   variable yytext and its length in yyleng.*/

extern char *yytext;
extern int yyleng;

/* The file from which lex will read input tokens (default is stdin). */
extern FILE *yyin;

/* Function to set yyin to another file */
void yyrestart( FILE *new_file );

/* The lexing function generated by lex: a token should be lexed with
   each call and its id returned. */
int yylex();

#endif
